on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update Blog Outline
        uses: wuzhe0912/wuzhe0912@master
